version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    # networks:
    #   - app-tier1
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.134.199.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: test:2:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - app-tier1
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - ./:/server
    # networks:
    #   - app-tier1


# networks:
#   app-tier1: