version: '3'

services:
  redis:
    image: 'docker.io/bitnami/redis'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - service-network
  server:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - '5000:8080'
    networks:
      - service-network
    volumes:
      - './:/server'

volumes:
    redis_data:
        driver: local

networks:
  service-network:
    driver: bridge

